# Generated by Django 4.0.1 on 2022-01-31 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(auto_now_add=True, verbose_name='記録日')),
                ('menu', models.CharField(max_length=20, verbose_name='トレーニング名')),
                ('sets', models.IntegerField(verbose_name='セット数')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOutRepsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(blank=True, null=True, verbose_name='回数')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='重量')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.workoutrecord')),
            ],
        ),
    ]
