# Generated by Django 4.0.1 on 2022-02-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_workoutrecord_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutrecord',
            name='sets',
            field=models.IntegerField(default=1, verbose_name='セット数'),
            preserve_default=False,
        ),
    ]
