# Generated by Django 4.0.1 on 2022-02-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_workoutrecord_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutmenu',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Sun', '日曜日'), ('Mon', '月曜日'), ('Tue', '火曜日'), ('Wed', '水曜日'), ('Thu', '木曜日'), ('Fri', '金曜日'), ('Sat', '土曜日')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='workoutmenu',
            name='parts',
            field=models.CharField(choices=[('arm', '腕'), ('chest', '胸'), ('shoulder', '肩'), ('back', '背中'), ('abdominal', '腹筋'), ('leg', '足'), ('others', 'その他')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutmenu',
            name='workout_type',
            field=models.CharField(choices=[('free', 'フリーウエイト'), ('machine', 'マシンウエイト'), ('bodyweight', '自重')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
