# Generated by Django 4.0.1 on 2022-02-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_workoutmenu_day_of_week_workoutmenu_parts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutmenu',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Sun', '日曜日'), ('Mon', '月曜日'), ('Tue', '火曜日'), ('Wed', '水曜日'), ('Thu', '木曜日'), ('Fri', '金曜日'), ('Sat', '土曜日')], max_length=3, null=True, verbose_name='トレーニング曜日'),
        ),
        migrations.AlterField(
            model_name='workoutmenu',
            name='parts',
            field=models.CharField(choices=[('arm', '腕'), ('chest', '胸'), ('shoulder', '肩'), ('back', '背中'), ('abdominal', '腹筋'), ('leg', '足'), ('others', 'その他')], max_length=10, verbose_name='部位'),
        ),
        migrations.AlterField(
            model_name='workoutmenu',
            name='workout_type',
            field=models.CharField(choices=[('free', 'フリーウエイト'), ('machine', 'マシンウエイト'), ('bodyweight', '自重')], max_length=10, verbose_name='トレーニングタイプ'),
        ),
    ]
