# Generated by Django 4.0.1 on 2022-02-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_workoutdetailrecord_remove_workoutrecord_memo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutdetailrecord',
            name='memo',
        ),
        migrations.AddField(
            model_name='workoutrecord',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
    ]
